inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Max: 120

NumericLiterals:
  Enabled: false
