db:
  image: postgres:9.4
  ports:
  - "5432:5432"
web:  
  build: .
  command: bundle exec puma -C config/puma.rb
  ports:
  - "3000:3000"
  volumes:
   - .:/app
  links:
  - db
  environment:
    DATABASE_HOST: db
    DATABASE_USER: postgres
