default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  pool: 5

development:
  <<: *default
  database: echo_development

test:
  <<: *default
  database: echo_test
